export const MIXPANEL_EVENTS = {
  pageView: 'Page View',
  search: 'Search',
  filterCity: 'Filter City',
  filterDate: 'Filter Date',
  lessonClick: 'Lesson Click',
  rabbiLogin: 'Rabbi Login',
  rabbiLogout: 'Rabbi Logout',
  panelTabClick: 'Panel Tab Click',
  lessonSaved: 'Lesson Saved',
  lessonDeleted: 'Lesson Deleted',
  occurrenceCancelled: 'Occurrence Cancelled',
  occurrenceRestored: 'Occurrence Restored',
  occurrenceMoved: 'Occurrence Moved',
  profileSaved: 'Profile Saved',
  profilePhotoUploaded: 'Profile Photo Uploaded',
} as const;
